config/routes.rb
Rails.application.routes.draw do
  root to: 'news#index'
  get '/search', to: 'news#search', as: 'search_news'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/news_controller.rb
require_relative '../services/news_service'
require_relative '../services/location_service'

class NewsController < ApplicationController
  def index
    @articles = NewsService.search('news', LocationService.get_country_code(request))
  end

  def search
    search_query = params[:q]
    if search_query.blank?
      flash[:error] = "Please enter a search query."
      redirect_to root_path
    else
      @articles = NewsService.search(search_query, LocationService.get_country_code(request))
      render :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsNewsapi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/news/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Latest News</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <div class="main-container">
      <h1>Latest News</h1>

        <%= form_tag search_news_path, method: :get do %>
            <%= text_field_tag :q, params[:q], placeholder: "Search news..." %>
            <%= submit_tag "Search" %>
            <% if flash[:error] %>
            <div class="error-container">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
        <% end %>

      <div class="main-container">
          <% @articles.each do |article| %>
            <% published_at = Time.parse(article['publishedAt']) %>

            <div class="article-container">
              <div class="title-container">
                <h2><%= article['title'] %></h2>
              </div>

              <div class="description-container">
                <p><%= article['description'] %></p>

                <div>
                  <p style="float: left;">Published at: <%= published_at.strftime('%H:%M %d/%m/%Y') %></p>
                  <a href="<%= article['url'] %>" style="float: right;">Read More</a>
                  <div style="clear: both;"></div>
                </div>
              </div>

              <div class="image-container">
                <p><%= image_tag article['image'], style: "max-width: 90%; height: auto;" %></p>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </body>
</html>